### ISSUE TITLE
BUILD_SHARED_LIBS link issue

### ISSUE THREAD

**Issue by rfabbri** [vxl/vxl#315]
When linking my app with with `BUILD_SHARED_LIBS = ON`,

It asks for a .a archive instead

`make[2]: *** No rule to make target `/Users/rfabbri/cprg/vxlprg/vxl-bin/lib/libvbl.a', needed by `basic/dbbl/tests/dbbl_test_include'.  `

Any hints? my cmakelists are a bit old, not sure what changed with BUILD_SHARED handling.

The cmake instruction to link the executable is:

`target_link_libraries( dbbl_test_all ${VXL_LIB_PREFIX}vbl ${VXL_LIB_PREFIX}testlib  )
`
Thanks.

**Comment by rfabbri** [comment]
I'm working on this in OSX 10.11.6. Some failed attempts:
- updated cmake to git
- updated CmakeLists.txt's in my app to mimmick VXL

I'm now moving to fine combing:
- looking into git log for vxl CMakeLists.txt to catch some related changes.
- writing a minimal app that uses vxl, to reproduce the error

Anyone else ran into this?

**Comment by rfabbri** [comment]
Ok, so here's the update. 

- looking into git log, a few things have changed in the build process no changes helped solve the problem
- writing a minimal app, this is what I found so far:
-- I can link to vul when changing target_link_libraries (while not including any header) but no other lib.
-- When including a header from vul I get an error
```
[ 50%] Building CXX object CMakeFiles/hello.dir/hello.o
In file included from /Users/rfabbri/cprg/vxlprg/hello-vxl/hello.cxx:3:
In file included from /Users/rfabbri/cprg/vxlprg/vxl/core/vul/vul_printf.h:24:
/Users/rfabbri/cprg/vxlprg/vxl/vcl/vcl_compiler.h:951:11: fatal error: 'tr1/memory' file not found
# include <tr1/memory>
          ^
1 error generated. 
```

The minimal app `hello-vxl` can be obtained here: 

The `hello-vxl` was coded by updating obsolete info from the vxl book while looking at recent changes to the vxl build system from the gitlog.

Looking into `VXLConfig.cmake`, I get installed system paths where I should have just my uninstalled 'vxl-bin' binary path. 

Here is the current `VXLConfig.cmake` from `vxl-bin/config/cmake/export`. Notice the paths are in the system's `/usr/local', which is not what I want.

```
# vxl/config/cmake/VXLConfig_export.cmake.in
#   also configured by CMake to
# /Users/rfabbri/cprg/vxlprg/vxl-bin/config/cmake/export/VXLConfig.cmake
#
# This CMake module is configured by VXL's build process to export the
# project settings for use by client projects.  A client project may
# find VXL and include this module using the FIND_PACKAGE command:
#
#  find_package(VXL)
#
# After this command executes, projects may test VXL_FOUND for whether
# VXL has been found.  If so, the settings listed below in this file
# have been loaded and are available for use.
#
# Typically, a client project will include UseVXL.cmake from the
# directory specified by the VXL_CMAKE_DIR setting:
#
#  find_package(VXL)
#  if(VXL_FOUND)
#    include(${VXL_CMAKE_DIR}/UseVXL.cmake)
#  else()
#    message("VXL_DIR should be set to the VXL build directory.")
#  endif()
#
# See vxl/config/cmake/UseVXL.cmake for details.
#

# The build settings file.
set(VXL_BUILD_SETTINGS_FILE "")

# The VXL library directory.
set(VXL_LIBRARY_DIR "/usr/local/lib")

# The VXL CMake support directory.
# Clients projects should not use the Find*.cmake files in this directory.
set(VXL_CMAKE_DIR "/usr/local/share/vxl/cmake")

# VXL Configuration options. You don't have to build with the same options as VXL, but it often helps.
set(VXL_BUILD_SHARED_LIBS "ON")
set(VXL_BUILD_TESTS "")
set(VXL_BUILD_EXAMPLES "ON")
set(VXL_EXTRA_CMAKE_CXX_FLAGS "")
set(VXL_EXTRA_CMAKE_C_FLAGS "")
set(VXL_EXTRA_CMAKE_EXE_LINKER_FLAGS "")
set(VXL_EXTRA_CMAKE_MODULE_LINKER_FLAGS "")
set(VXL_EXTRA_CMAKE_SHARED_LINKER_FLAGS "")

# VXL has many parts that are optional, depending on selections made
# when building.  The stanzas below give a consistent (though
# pedantic) interface to each part.  Clients use these settings to
# determine whether a part was built (_FOUND), where its headers are
# located (_INCLUDE_DIR) and in some cases what libraries must be
# linked to use the part (_LIBRARIES).  Most client projects will
# likely still refer to individual VXL libraries such as vcl, for
# example, by hard-wired "vcl" instead of using the variable
# VXL_VCL_LIBRARIES, but it is there just in case.

set(VXL_VCL_FOUND "YES" ) # VXL vcl is always FOUND.  It is not optional.
set(VXL_VCL_INCLUDE_DIR "/usr/local/include/vxl/vcl")
set(VXL_VCL_LIBRARIES "vcl")

set(VXL_CORE_FOUND "YES" ) # VXL core is always FOUND.  It is not optional.
set(VXL_CORE_INCLUDE_DIR "/usr/local/include/vxl/core")
# VXL core has many libraries

set(VXL_CORE_VIDEO_FOUND "ON" )
set(VXL_CORE_VIDEO_INCLUDE_DIR "/usr/local/include/vxl/core")
set(VXL_CORE_VIDEO_LIBRARIES "vidl")
set(VXL_CORE_VIDEO_FFMPEG_FOUND "ON" )

set(VXL_VGUI_FOUND "YES")
set(VXL_VGUI_INCLUDE_DIR "/System/Library/Frameworks/OpenGL.framework")
set(VXL_VGUI_LIBRARIES "vgui")

set(VXL_VGUI_WX_FOUND "")

set(VXL_CONTRIB_FOUND "ON")
# VXL contrib has subdirectories handled independently below
# VXL contrib has many libraries

set(VXL_BRL_FOUND "ON")
set(VXL_BRL_INCLUDE_DIR "/usr/local/include/vxl/contrib/brl;/usr/local/include/vxl/contrib/brl/bbas;/usr/local/include/vxl/contrib/brl/bseg;/usr/local/include/vxl/contrib/brl/bpro")
# VXL BRL has many libraries

set(VXL_BGUI3D_FOUND "NO")
set(VXL_BGUI3D_INCLUDE_DIR "")

set(VXL_COIN3D_FOUND "")
set(VXL_COIN3D_INCLUDE_DIR "")

set(VXL_GEL_FOUND "ON")
set(VXL_GEL_INCLUDE_DIR "/usr/local/include/vxl/contrib/gel")
# VXL GEL has many libraries

set(VXL_MUL_FOUND "ON")
set(VXL_MUL_INCLUDE_DIR "/usr/local/include/vxl/contrib/mul")
# VXL MUL has many libraries

set(VXL_OUL_FOUND "ON")
set(VXL_OUL_INCLUDE_DIR "/usr/local/include/vxl/contrib/oul")
# VXL OUL has many libraries

set(VXL_OXL_FOUND "ON")
set(VXL_OXL_INCLUDE_DIR "/usr/local/include/vxl/contrib/oxl")
# VXL OXL has many libraries

set(VXL_PRIP_FOUND "ON")
set(VXL_PRIP_INCLUDE_DIR "/usr/local/include/vxl/contrib/prip")
# VXL PRIP has many libraries

set(VXL_RPL_FOUND "ON")
set(VXL_RPL_RGTL_FOUND "OFF")
set(VXL_RPL_INCLUDE_DIR "/usr/local/include/vxl/contrib/rpl")
# VXL RPL has many libraries

set(VXL_TBL_FOUND "ON")
set(VXL_TBL_INCLUDE_DIR "/usr/local/include/vxl/contrib/tbl")
# VXL TBL has many libraries

set(VXL_CONVERSIONS_FOUND "ON")
set(VXL_CONVERSIONS_INCLUDE_DIR "/usr/local/include/vxl/contrib/conversions")
# VXL CONVERSIONS has no libraries

set(VXL_TARGETJR_FOUND "")

# Client projects use these setting to find and use the 3rd party
# libraries that VXL either found on the system or built for itself.
# Sometimes, VXL will point client projects to the library VXL built
# for itself, and sometimes VXL will point client projects to the
# system library it found.

set(VXL_NETLIB_FOUND "YES")
set(VXL_NETLIB_INCLUDE_DIR "/usr/local/include/vxl/v3p/netlib")
set(VXL_NETLIB_LIBRARIES "netlib;v3p_netlib")

set(VXL_ZLIB_FOUND "TRUE")
set(VXL_ZLIB_INCLUDE_DIR "")
set(VXL_ZLIB_LIBRARIES "/opt/local/lib/libz.dylib")

set(VXL_PNG_FOUND "TRUE")
set(VXL_PNG_INCLUDE_DIR "")
set(VXL_PNG_LIBRARIES "/opt/local/lib/libpng.dylib;/opt/local/lib/libz.dylib")

set(VXL_JPEG_FOUND "TRUE")
set(VXL_JPEG_INCLUDE_DIR "")
set(VXL_JPEG_LIBRARIES "/opt/local/lib/libjpeg.dylib")

set(VXL_TIFF_FOUND "TRUE")
set(VXL_TIFF_INCLUDE_DIR "/opt/local/include")
set(VXL_TIFF_LIBRARIES "/opt/local/lib/libtiff.dylib")

set(VXL_GEOTIFF_FOUND "YES")
set(VXL_GEOTIFF_INCLUDE_DIR "/Users/rfabbri/cprg/vxlprg/vxl/v3p/geotiff")
set(VXL_GEOTIFF_LIBRARIES "geotiff")

set(VXL_MPEG2_FOUND "")
set(VXL_MPEG2_INCLUDE_DIR "")
set(VXL_MPEG2_LIBRARIES "")

set(VXL_COIN3D_FOUND "")
set(VXL_COIN3D_INCLUDE_DIR "")
set(VXL_COIN3D_LIBRARY "")

set(VXL_PYTHON_FOUND "NO")
set(VXL_PYTHON_INCLUDE_PATH "")
set(VXL_PYTHON_PC_INCLUDE_PATH "")
set(VXL_PYTHON_LIBRARY "")
set(VXL_PYTHON_DEBUG_LIBRARY "")

set(VXL_EXPAT_FOUND "TRUE")
set(VXL_EXPAT_INCLUDE_DIR "")
set(VXL_EXPAT_LIBRARIES "/opt/local/lib/libexpat.dylib")

# Tell UseVXL.cmake that VXLConfig.cmake has been included.
set(VXL_CONFIG_CMAKE 1)

# Import VXL targets.
if(NOT VXL_TARGETS_IMPORTED)
  set(VXL_TARGETS_IMPORTED 1)
  include("${CMAKE_CURRENT_LIST_DIR}/VXLTargets.cmake")
endif()

```

**Here is the old one (notice paths are in my home dir, which is what I want),:**

```
# vxl/config/cmake/VXLConfig.cmake.in
#   also configured by CMake to
# /home/rfabbri/cprg/vxlprg/vxl-bin/VXLConfig.cmake
#
# This CMake module is configured by VXL's build process to export the
# project settings for use by client projects.  A client project may
# find VXL and include this module using the FIND_PACKAGE command:
#
#  FIND_PACKAGE(VXL)
#
# After this command executes, projects may test VXL_FOUND for whether
# VXL has been found.  If so, the settings listed below in this file
# have been loaded and are available for use.
#
# Typically, a client project will include UseVXL.cmake from the
# directory specified by the VXL_CMAKE_DIR setting:
#
#  FIND_PACKAGE(VXL)
#  IF(VXL_FOUND)
#    INCLUDE(${VXL_CMAKE_DIR}/UseVXL.cmake)
#  ELSE(VXL_FOUND)
#    MESSAGE("VXL_DIR should be set to the VXL build directory.")
#  ENDIF(VXL_FOUND)
#
# See vxl/config/cmake/UseVXL.cmake for details.
#

# The build settings file.
SET(VXL_BUILD_SETTINGS_FILE "/home/rfabbri/cprg/vxlprg/vxl-bin/VXLBuildSettings.cmake")

# The VXL library dependencies.
IF(NOT VXL_NO_LIBRARY_DEPENDS)
  INCLUDE("/home/rfabbri/cprg/vxlprg/vxl-bin/VXLLibraryDepends.cmake")
ENDIF(NOT VXL_NO_LIBRARY_DEPENDS)

# The VXL library directory.
SET(VXL_LIBRARY_DIR "/home/rfabbri/cprg/vxlprg/vxl-bin/lib")

# The VXL CMake support directory.
# Clients projects should not use the Find*.cmake files in this directory.
SET(VXL_CMAKE_DIR "/home/rfabbri/cprg/vxlprg/vxl/config/cmake/Modules")

# VXL Configuration options. You don't have to build with the same options as VXL, but it often helps.
SET(VXL_BUILD_SHARED_LIBS "ON")
SET(VXL_BUILD_TESTS "")
SET(VXL_BUILD_EXAMPLES "OFF")
SET(VXL_EXTRA_CMAKE_CXX_FLAGS "")
SET(VXL_EXTRA_CMAKE_C_FLAGS "")
SET(VXL_EXTRA_CMAKE_EXE_LINKER_FLAGS "")
SET(VXL_EXTRA_CMAKE_MODULE_LINKER_FLAGS "")
SET(VXL_EXTRA_CMAKE_SHARED_LINKER_FLAGS "")

# VXL has many parts that are optional, depending on selections made
# when building.  The stanzas below give a consistent (though
# pedantic) interface to each part.  Clients use these settings to
# determine whether a part was built (_FOUND), where its headers are
# located (_INCLUDE_DIR) and in some cases what libraries must be
# linked to use the part (_LIBRARIES).  Most client projects will
# likely still refer to individual VXL libraries such as vcl, for
# example, by hard-wired "vcl" instead of using the variable
# VXL_VCL_LIBRARIES, but it is there just in case.

SET(VXL_VCL_FOUND "YES" ) # VXL vcl is always FOUND.  It is not optional.
SET(VXL_VCL_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl-bin/vcl;/home/rfabbri/cprg/vxlprg/vxl/vcl")
SET(VXL_VCL_LIBRARIES "vcl")

SET(VXL_CORE_FOUND "YES" ) # VXL core is always FOUND.  It is not optional.
SET(VXL_CORE_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl-bin/core;/home/rfabbri/cprg/vxlprg/vxl/core")
# VXL core has many libraries

SET(VXL_CORE_VIDEO_FOUND "YES" )
SET(VXL_CORE_VIDEO_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl-bin/core;/home/rfabbri/cprg/vxlprg/vxl/core")
SET(VXL_CORE_VIDEO_LIBRARIES "vidl1 vidl_vil1 vidl")

SET(VXL_VGUI_FOUND "YES")
SET(VXL_VGUI_INCLUDE_DIR "/usr/include")
SET(VXL_VGUI_LIBRARIES "vgui")

SET(VXL_VGUI_WX_FOUND "")

SET(VXL_CONTRIB_FOUND "ON")
# VXL contrib has subdirectories handled independently below
# VXL contrib has many libraries

SET(VXL_BRL_FOUND "ON")
SET(VXL_BRL_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/contrib/brl/bbas;/home/rfabbri/cprg/vxlprg/vxl-bin/contrib/brl/bbas;/home/rfabbri/cprg/vxlprg/vxl/contrib/brl/bseg;/home/rfabbri/cprg/vxlprg/vxl/contrib/brl/bmvl;/home/rfabbri/cprg/vxlprg/vxl/contrib/brl/bpro;/home/rfabbri/cprg/vxlprg/vxl/contrib/brl")
# VXL BRL has many libraries

SET(VXL_BGUI3D_FOUND "OFF")
SET(VXL_BGUI3D_INCLUDE_DIR "")

SET(VXL_COIN3D_FOUND "")
SET(VXL_COIN3D_INCLUDE_DIR "")

SET(VXL_GEL_FOUND "ON")
SET(VXL_GEL_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/contrib/gel")
# VXL GEL has many libraries

SET(VXL_MUL_FOUND "ON")
SET(VXL_MUL_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/contrib/mul")
# VXL MUL has many libraries

SET(VXL_OUL_FOUND "ON")
SET(VXL_OUL_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/contrib/oul")
# VXL OUL has many libraries

SET(VXL_OXL_FOUND "ON")
SET(VXL_OXL_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/contrib/oxl")
# VXL OXL has many libraries

SET(VXL_RPL_FOUND "ON")
SET(VXL_RPL_RGTL_FOUND "OFF")
SET(VXL_RPL_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/contrib/rpl")
# VXL RPL has many libraries

SET(VXL_TBL_FOUND "ON")
SET(VXL_TBL_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/contrib/tbl")
# VXL TBL has many libraries

SET(VXL_CONVERSIONS_FOUND "ON")
SET(VXL_CONVERSIONS_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/contrib/conversions")
# VXL CONVERSIONS has no libraries

SET(VXL_TARGETJR_FOUND "OFF")

# Client projects use these setting to find and use the 3rd party
# libraries that VXL either found on the system or built for itself.
# Sometimes, VXL will point client projects to the library VXL built
# for itself, and sometimes VXL will point client projects to the
# system library it found.

SET(VXL_NETLIB_FOUND "YES")
SET(VXL_NETLIB_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/v3p/netlib")
SET(VXL_NETLIB_LIBRARIES "netlib;v3p_netlib")

SET(VXL_QV_FOUND "YES")
SET(VXL_QV_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/v3p")
SET(VXL_QV_LIBRARIES "Qv")

SET(VXL_ZLIB_FOUND "TRUE")
SET(VXL_ZLIB_INCLUDE_DIR "/usr/include")
SET(VXL_ZLIB_LIBRARIES "/lib/libz.so")

SET(VXL_PNG_FOUND "TRUE")
SET(VXL_PNG_INCLUDE_DIR "/usr/include;/usr/include")
SET(VXL_PNG_LIBRARIES "/usr/lib/libpng.so;/lib/libz.so")

SET(VXL_JPEG_FOUND "TRUE")
SET(VXL_JPEG_INCLUDE_DIR "/usr/include")
SET(VXL_JPEG_LIBRARIES "/usr/lib/libjpeg.so")

SET(VXL_TIFF_FOUND "TRUE")
SET(VXL_TIFF_INCLUDE_DIR "/usr/include")
SET(VXL_TIFF_LIBRARIES "/usr/lib/libtiff.so")

SET(VXL_GEOTIFF_FOUND "YES")
SET(VXL_GEOTIFF_INCLUDE_DIR "/home/rfabbri/cprg/vxlprg/vxl/v3p/geotiff")
SET(VXL_GEOTIFF_LIBRARIES "geotiff")

SET(VXL_MPEG2_FOUND "TRUE")
SET(VXL_MPEG2_INCLUDE_DIR "/usr/include")
SET(VXL_MPEG2_LIBRARIES "/usr/lib/libmpeg2.so;MPEG2_vo_LIBRARY-NOTFOUND;/usr/lib/libSDLmain.a;/usr/lib/libSDL.so;-lpthread")

SET(VXL_RPLY_FOUND "")
SET(VXL_RPLY_INCLUDE_DIR "")
SET(VXL_RPLY_LIBRARIES "")

SET(VXL_COIN3D_FOUND "")
SET(VXL_COIN3D_INCLUDE_DIR "")
SET(VXL_COIN3D_LIBRARY "")

SET(VXL_PYTHON_FOUND "YES")
SET(VXL_PYTHON_INCLUDE_PATH "/usr/include/python2.5")
SET(VXL_PYTHON_PC_INCLUDE_PATH "")
SET(VXL_PYTHON_LIBRARY "/usr/lib/python2.5/config/libpython2.5.a")
SET(VXL_PYTHON_DEBUG_LIBRARY "")

SET(VXL_EXPAT_FOUND "TRUE")
SET(VXL_EXPAT_INCLUDE_DIR "/usr/include")
SET(VXL_EXPAT_LIBRARIES "/usr/lib/libexpat.so")

# Tell UseVXL.cmake that VXLConfig.cmake has been included.
SET(VXL_CONFIG_CMAKE 1)

### deprecated variables set below ###
# These should be removed after some time to upgrade has passed.

# VXL include directories.
# There is no need for clients to use this directly
SET(VXL_V3P_INCLUDE_DIR_deprecated "/home/rfabbri/cprg/vxlprg/vxl/v3p")

# Would a client project need to use these variables ever?
# These are needed for backward compatibility mode for now, see UseVXL.cmake
SET(VXL_VGUI_USE_GLUT_deprecated "OFF")
SET(VXL_VGUI_USE_QT_deprecated "")
SET(VXL_VGUI_USE_MFC_deprecated "")
SET(VXL_VGUI_USE_GTK_deprecated "")
SET(VXL_VGUI_USE_GTK2_deprecated "ON")

# There is no need for clients to know this.
# These are needed for backward compatibility mode for now, see UseVXL.cmake
SET(VXL_FORCE_V3P_ZLIB_deprecated "OFF")
SET(VXL_FORCE_V3P_JPEG_deprecated "OFF")
SET(VXL_FORCE_V3P_TIFF_deprecated "OFF")
SET(VXL_FORCE_V3P_GEOTIFF_deprecated "OFF")
SET(VXL_FORCE_V3P_PNG_deprecated "OFF")
SET(VXL_FORCE_V3P_MPEG2_deprecated "OFF")
SET(VXL_FORCE_V3P_RPLY_deprecated "")

```

**Comment by rfabbri** [comment]
OK, a clean rebuild of vxl makes the hello-vxl program build, for both BUILD_SHARED_LIBS on and off. 
There was probably some kind of thrash left around in my bin compile folders which I overlooked.
Silly well-known mistake, but I hope thats it.

**Comment by rfabbri** [comment]
Recompiling both vxl and my app carefully with libstdc++ per the command:
`cmake -DCMAKE_CXX_FLAGS:STRING="-Wno-gnu-static-float-init -stdlib=libstdc++" ../vxl`
Solves this issue.
