### ISSUE TITLE
error C2668: 'fpclassify': ambiguous call to overloaded function

### ISSUE THREAD

**Issue by dzenanz** [vxl/vxl#843]
### Description

Current master fails to compile with Visual Studio 2019 version 16.10.0.

### Steps to Reproduce

1. git clone
2. Configure using CMake's default options
3. Build in Visual Studio

### Expected behavior

The project should compile without errors.

### Actual behavior

```text
1>test_math_value_range.cxx
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h(413,1): error C2668: 'fpclassify': ambiguous call to overloaded function
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h(298,31): message : could be 'int fpclassify(long double) throw()'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h(293,31): message : or       'int fpclassify(double) throw()'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h(288,31): message : or       'int fpclassify(float) throw()'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h(413,1): message : while trying to match the argument list '(_Ty)'
1>        with
1>        [
1>            _Ty=vxl_byte
1>        ]
1>M:\Dev\vxl\core\vil/vil_math.h(127): message : see reference to function template instantiation 'bool isnan<T>(_Ty) throw()' being compiled
1>        with
1>        [
1>            T=vxl_byte,
1>            _Ty=vxl_byte
1>        ]
1>M:\Dev\vxl\core\vil\tests\test_math_value_range.cxx(86): message : see reference to function template instantiation 'void vil_math_value_range_percentiles<vxl_byte>(const vil_image_view<vxl_byte> &,const std::vector<double,std::allocator<double>> &,std::vector<T,std::allocator<T>> &,bool)' being compiled
1>        with
1>        [
1>            T=vxl_byte
1>        ]
1>M:\Dev\vxl\core\vil\tests\test_math_value_range.cxx(128): message : see reference to function template instantiation 'void _test_math_value_range<vxl_byte>(std::string,bool)' being compiled
1>Done building project "vil_test_all.vcxproj" -- FAILED.
```
### Reproducibility

100%

### Versions

Current master, which is also tagged as 3.3.0.

### Environment

This probably happens on all recent versions of VS2019.

**Comment by decrispell** [comment]
fixed via #852
